language: php

services:
  - docker

php:
  - 7.1

notifications:
  email:
    on_success: never
    on_failure: change


env:
  matrix:
    - PHP_VERSION=5.3 WP_VERSION=4.3.6
    - PHP_VERSION=5.3 WP_VERSION=latest
    - PHP_VERSION=5.3 WP_VERSION=trunk
    - PHP_VERSION=7.1 WP_VERSION=4.3.6
    - PHP_VERSION=7.1 WP_VERSION=latest
    - PHP_VERSION=7.1 WP_VERSION=trunk

  global:
    - SVN_REPO: https://plugins.svn.wordpress.org/custom-post-type-permalinks/
    - secure: "G6ugr3v6cOwWCh8sDsqn4NfJ74zO68n1xwDmPOjkhMr0jhnwdNcPgQzVA5WXf/8yV5I910UAm3XQrT5CajXgwt2Tcsli67Olu3R8Nqcwh0lqAK5Q4LdD5RoP2Ie2jY/ih4Z56CZEhiuZbG9Qp/YeN8j/kIEDf/y/VwzoX/s3OXI="


matrix:
  include:
      env: PHP_VERSION=5.3 WP_VERSION=latest WP_PULUGIN_DEPLOY=1
  allow_failures:
    - env: PHP_VERSION=5.3 WP_VERSION=trunk
    - env: PHP_VERSION=7.1 WP_VERSION=trunk

before_script:
  - curl -L https://raw.githubusercontent.com/torounit/wpenv/issue/support-nightly/run.sh | bash -s $PHP_VERSION $WP_VERSION
  - docker exec -it -u root wpenv ln -s /home/ubuntu/.phpenv/shims/php /usr/local/bin/
  - docker exec -it -u root wpenv ln -s /home/ubuntu/.phpenv/shims/composer /usr/local/bin/
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      if [[ ${PHP_VERSION:0:2} == "5." ]]; then
        docker exec wpenv composer global require "phpunit/phpunit=4.8.*"
      else
        docker exec wpenv composer global require "phpunit/phpunit=5.7.*"
      fi
    fi
  - |
  - docker exec -it -u root wpenv ln -s /home/ubuntu/.phpenv/shims/phpunit /usr/local/bin/
  - docker exec -it -u $(id -u) wpenv composer install

script:
  - docker exec -it -u $(id -u) wpenv composer phpcs
  - docker exec wpenv phpunit
  - docker exec -e WP_MULTISITE=1 wpenv phpunit

after_success: curl -L https://raw.githubusercontent.com/miya0001/travis2wpplugin/master/deploy.sh | bash

